### ISSUE TITLE
bad interpreter on osx

### ISSUE THREAD

**Issue by inagun** [codescapade/aeons#1]
On osx call aeons command answer : -bash: /usr/local/bin/aeons: /bin/sh^M: bad interpreter: No such file or directory
i had to use dos2unix on /usr/local/bin/aeons file to convert.
probably a problem with you editor configuration.

**Comment by codescapade** [comment]
I'm getting the same now. When I tested this before uploading to haxelib it worked fine. Maybe this happened because I zipped and uploaded the library from windows. I'll look into it.

**Comment by codescapade** [comment]
Was an issue with the git line ending config. Uploaded a new haxelib version with a fix.
